- name: "Don't commit"
  pattern: '@?[dDsD][oO][nN][tT]_?[cC][oO][mM]{1,3}[iI][tT]'
  filePattern: .*

- name: Perl printf debugger
  pattern: '^print\s+STDERR'
  filePattern: .*\.(pl|pm|t)

- name: Perl Data::Dumper debugging
  pattern: 'Data::Dumper'
  filePattern: .*\.(pl|pm|t)

- name: POD in markdown
  pattern: '\n=\w+'
  filePattern: .*\.md
