- name: "Don't commit"
  pattern: "@?[dDsD][oO][nN][tT]_?[cC][oO][mM]{1,3}[iI][tT]"
  filename:
    - "*"
  error: true

- name: Perl printf debugger
  pattern: "^print STDERR"
  filename:
     - "*.pl"
     - "*.pm"
     - "*.t"
  error: true

- name: Perl Data::Dumper debugging
  pattern: "use Data::Dumper;"
  filename:
     - "*.pl"
     - "*.pm"
     - "*.t"
  error: true

- name: POD in markdown
  pattern: '\n=\w+'
  filename:
    - "*.md"
  error: true
