---
on: [push]  # yamllint disable-line rule:truthy
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.22'
          - '5.30'
          - '5.36'
          - 'latest'
    container:
      # https://hub.docker.com/r/perldocker/perl-tester
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    steps:
      - name: Build, test, collect coverage on Perl ${{ matrix.perl-version }}
        uses: actions/checkout@v3
      - run sudo apt-get install aspell libaspell-dev aspell-en aspell-de
      - run: perl --version
      - run: cpanm --installdeps --notest .
      - run: perl Makefile.PL
      - run: make cover
