---
# Losely based on https://perlmaven.com/setup-github-actions
on: [push]  # yamllint disable-line rule:truthy
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Build and test on latest MacOS
        uses: actions/checkout@v3

      - run: perl --version
      - run: brew bundle
      - run: export PATH="/usr/local/opt/libxml2/bin:$PATH"
      - run: cpanm --installdeps --notest .
      - run: perl Makefile.PL
      - run: make test
