---
on: [push]  # yamllint disable-line rule:truthy
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Build and test on latest MacOS
        uses: actions/checkout@v3

      - run: perl --version
      - run: brew bundle
      # Needs to set the PATH so that it finds the newer libxml installed with brew
      # instead of the older OS version.
      - run: PATH="/usr/local/opt/libxml2/bin/:$PATH" cpanm --installdeps --notest .
      - run: cpanm install Tie::IxHash

      - run: perl Makefile.PL
      - run: make test
