---
on: [push]  # yamllint disable-line rule:truthy
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Build and test on latest MacOS
        uses: actions/checkout@v3

      - run: perl --version
      - run: brew bundle
      # Swap out Aspell for Hunspell before installing dependencies.
      # Aspell needs some native libraries and header files.
      # Hunspell depends on ExtUtils::GuessCpp, which as of May 2024 has failing tests
      # on MacOS, so skip its tests here.
      - run: cpanm install --notest Text::Hunspell
      - run: perl -p -e 's/Text::Aspell/Text::Hunspell/mg' -i Makefile.PL
      # Needs to set the PATH so that it finds the newer libxml installed with brew
      # instead of the older OS version.
      - run: PATH="/usr/local/opt/libxml2/bin/:$PATH" cpanm --installdeps --notest .
      - run: cpanm install Tie::IxHash

      - run: perl Makefile.PL
      - run: make test
